---

- name: Install tasks
  become: true
  tags:
    - redis_install
    - redis
  block:

    - name: Install redis package
      when: ansible_os_family == 'Debian'
      ansible.builtin.apt:
        name: ["{{ item }}"]
        update_cache: true
        state: "{{ redis_package_ensure }}"
      with_items: "{{ redis_package_name }}"

    # TODO
    #- name: Install redis package
    #  when: ansible_os_family == 'RedHat'
    #  ansible.builtin.yum:
    #    name: ["{{ item }}"]
    #    state: "{{ redis_package_ensure }}"
    #  with_items: "{{ redis_package_name }}"
